apiVersion: skaffold/v2beta9
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  # googleCloudBuild:
  #   projectId: schoolable-295414
  artifacts:
    - image: gustafdahl/auth
      # kaniko:
      #     dockerfile: Dockerfile.dev
      #     cache: {}
      context: auth
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: gustafdahl/admin-dashboard
    # kaniko:
    #     dockerfile: Dockerfile.dev
    #     cache: {}
      context: admin-dashboard
      docker:
        dockerfile: Dockerfile.dev
      sync:
          manual:
            - src: 'src/**/*.ts'
              dest: .
    - image: gustafdahl/admin-dashboard-client
      # kaniko:
      #     dockerfile: Dockerfile.dev
      #     cache: {}
      context: admin-dashboard-client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: 'src/*'
            dest: .
          - src: 'public/*'
            dest: .
# cluster:
#   namespace: logging
