apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s
build:
  googleCloudBuild:
    projectId: schoolable-295414
  artifacts:
    - image: us.gcr.io/schoolable-295414/auth
      kaniko:
          dockerfile: Dockerfile
          cache: {}
      context: auth
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
