apiVersion: skaffold/v2beta9
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  googleCloudBuild:
    projectId: schoolable-295414
  artifacts:
    - image: us.gcr.io/schoolable-295414/auth
      kaniko:
          dockerfile: Dockerfile.dev
          cache: {}
      context: auth
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: us.gcr.io/schoolable-295414/admin-dashboard
      kaniko:
          dockerfile: Dockerfile.dev
          cache: {}
      context: admin-dashboard
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: us.gcr.io/schoolable-295414/admin-dashboard-client
      kaniko:
          dockerfile: Dockerfile.dev
          cache: {}
      context: admin-dashboard-client
      sync:
        manual:
          - src: 'src/*'
            dest: .
          - src: 'public/*'
            dest: .
# cluster:
#   namespace: logging
