# apiVersion: v1
# kind: Namespace
# metadata:
#   name: logging
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  # namespace: logging
  name: kibana
  labels:
    component: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
     component: kibana
  template:
    metadata:
      labels:
        component: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana-oss:7.9.3
          env:
            - name: CLUSTER_NAME
              value: my-es
            - name: ELASTICSEARCH_URL
              value: http://elasticsearch:9200
          resources:
            limits:
              cpu: 200m
            requests:
              cpu: 100m
          ports:
            - containerPort: 5601
              name: http
---
apiVersion: v1
kind: Service
metadata:
  # namespace: logging
  name: kibana
  annotations:
    # cloud.google.com/load-balancer-type: "Internal"
    service.kubernetes.io/load-balancer-cleanup: "true"
  labels:
    component: kibana
spec:
  selector:
    component: kibana
  ports:
    - name: http
      port: 5601
      targetPort: 5601
      protocol: TCP
  type: LoadBalancer
