apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
    # kubernetes.io/ingress.global-static-ip-name: "admin-dashboard"
spec:
  tls:
    - secretName: ca-key-pair
  rules:
    - host: admin.schoolable.se
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: admin-dashboard-client-srv
              servicePort: 3000
    - host: dev.schoolable.se
      http:
        paths:
          - path: /api/users/?(.*)
            backend:
              serviceName: auth-srv
              servicePort: 3000
          # - path: /http://35.228.57.1/
          #   backend:
          #     serviceName: elasticsearch-srv
          #     servicePort: 9200
          # - path: /?(.*)
          #   backend:
          #     serviceName: client-srv
          #     servicePort: 3000
